insert into t_user (id,user_id,name,email) values(1,'ogm','Oscar','oscar@uncorreo.es')
insert into t_user (id,user_id,name,email) values(2,'peptio01','Pepito Pérez','pepitoperez@uncorreo.es')
insert into T_POSTIT(id,id_user,project_id,title,text,color) values(1,1,1,'Título - 1','Esto es el texto completo 1','#ffaabb')
insert into T_POSTIT(id,id_user,project_id,title,text,color) values(2,1,1,'Título - 2','Esto es el texto completo 2','#ffffff')
insert into T_POSTIT(id,id_user,project_id,title,text,color) values(3,1,1,'Título - 2','Esto es el texto completo 3','#aaaabb')
insert into t_project (id, description,title) values (1,'Descripcion','Título')
insert into t_project (id, description,title) values (2,'Descripcion2','Título2')
insert into user_projects (user_id,project_id) values (1,1)
insert into user_projects (user_id,project_id) values (1,2)