insert into t_user (id,user_id,name,email) values(1,'ogm','Oscar','oscar@uncorreo.es')
insert into t_user (id,user_id,name,email) values(2,'peptio01','Pepito Pérez','pepitoperez@uncorreo.es')
insert into t_project (id, description,title) values (1,'Descripcion','Titulo')
insert into t_project (id, description,title) values (2,'Descripcion2','Titulo2')
insert into T_POSTIT(id,id_user,PROJECT_ID,title,text,color) values(1,1,1,'Titulo 1-1','Esto es el texto completo','#ffaabb')
insert into T_POSTIT(id,id_user,PROJECT_ID,title,text,color) values(2,1,1,'Titulo 2-1','Esto es el texto completo','#ffaabb')
insert into T_POSTIT(id,id_user,PROJECT_ID,title,text,color) values(3,1,1,'Titulo 3-1','Esto es el texto completo','#ffaabb')
insert into T_POSTIT(id,id_user,PROJECT_ID,title,text,color) values(4,1,2,'Titulo 4-2','Esto es el texto completo','#ffaabb')
insert into user_projects (user_id,project_id) values (1,1)
insert into user_projects (user_id,project_id) values (1,2)